version: "3.9"

services:

  user-service:
    image: vzateychuk/user-service:5.0.0
    container_name: user-service
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_NAME: userdb
      DB_LOGIN: admin
      DB_PWD: pwd
    depends_on:
      - postgres-userdb

  postgres-userdb:
    image: postgres:15.3
    container_name: postgres-userdb
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
    ports:
      - "5433:5432"

  post-service:
    image: vzateychuk/post-service:5.0.0
    container_name: post-service
    restart: on-failure
    ports:
      - "8082:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5434
      DB_NAME: postdb
      DB_LOGIN: admin
      DB_PWD: pwd
      USER_SERVICE_API: http://host.docker.internal:8081/users/
    depends_on:
      - user-service
      - postgres-postdb

  postgres-postdb:
    image: postgres:15.3
    container_name: postgres-postdb
    restart: always
    environment:
      POSTGRES_DB: postdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
    ports:
      - "5434:5432"
