version: "3.9"

services:

  user-service:
    image: vzateychuk/user-service:2.0.0
    container_name: user-service
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      DB_JDBC: jdbc:h2:mem:userdb
      DB_LOGIN: sa
      DB_PWD: pwd

  post-service:
    image: vzateychuk/post-service:2.0.0
    container_name: post-service
    restart: on-failure
    ports:
      - "8082:8080"
    environment:
      DB_JDBC: jdbc:h2:mem:userdb
      DB_LOGIN: sa
      DB_PWD: pwd
      USER_SERVICE_API: http://host.docker.internal:8081/users/
    depends_on:
      - user-service
