version: "3.9"

services:

  user-service:
    image: vzateychuk/user-service:1.0.0
    container_name: user-service
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      SERVICE_PORT: 8081
      DB_JDBC: jdbc:h2:mem:userdb
      DB_LOGIN: sa
      DB_PASSW: pwd

  post-service:
    image: vzateychuk/post-service:1.0.0
    container_name: post-service
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SERVICE_PORT: 8082
      DB_JDBC: jdbc:h2:mem:userdb
      DB_LOGIN: sa
      DB_PASSW: pwd
      USER_SERVICE_API: http://user-service:8081/users/
    depends_on:
      - user-service
