apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-pv
  labels:
    type: local
    app: k8s-user-srv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"