apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
  namespace: k8s-vez
  labels:
    app: k8s-user-srv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi