apiVersion: v1
kind: Service
metadata:
  name: user-srv
  namespace: vez
spec:
  type: NodePort
  selector:
    app: usersrv
  ports:
    - name: http
      nodePort: 30081
      protocol: "TCP"
      port: 8081
      targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-user
  namespace: vez
  labels:
    app: vez-app
    owner: vzateychuk
spec:
  selector:
    matchLabels:
      app: usersrv
  replicas: 2
  template:
    metadata:
      labels:
        app: usersrv
        owner: vzateychuk
    spec:
      volumes:
        - name: user-store
          persistentVolumeClaim:
            claimName: user-pvc
      containers:
        - name: user-service
          image: vzateychuk/user-service:4.0.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/home/data"
              name: user-store
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-cfg    # The ConfigMap this value comes from
                  key: userdb_host # The key to fetch
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-cfg
                  key: userdb_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-cfg
                  key: user_db_name
            - name: DB_LOGIN
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: username
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: password

