apiVersion: v1
kind: Service
metadata:
  name: user-srv
  namespace: vez
spec:
  type: LoadBalancer
  selector:
    app: usersrv
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-user
  namespace: vez
  labels:
    app: vez-app
    owner: vzateychuk
spec:
  selector:
    matchLabels:
      app: usersrv
  replicas: 2
  template:
    metadata:
      labels:
        app: usersrv
        owner: vzateychuk
    spec:
      volumes:
        - name: user-store
          persistentVolumeClaim:
            claimName: user-pvc
      containers:
        - name: user-service
          image: vzateychuk/user-service:3.0.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/home/data"
              name: user-store
          env:
            - name: DB_HOST
              value: 10.110.61.113
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: userdb
            - name: DB_LOGIN
              value: admin
            - name: DB_PWD
              value: pwd

