apiVersion: v1
kind: Service
metadata:
  name: postdb-srv
  namespace: {{ .Values.namespace }}
  labels:
    app: postdb-srv
spec:
  selector:
    app: postdb
  type: ClusterIP
  clusterIP: 10.99.22.101
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postdb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: postdb # has to match .spec.template.metadata.labels
  serviceName: "postgre"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: postdb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postdb
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: post-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: post-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: post-cfg
                  key: post_db_name
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - name: post-vol
              mountPath: /data
            # db-initialization scripts will run as soon as container starts
            - name: dbinit
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        # see 'Initialization scripts' https://hub.docker.com/_/postgres
        - name: dbinit
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: post-cfg
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "post-schema.sql"
                path: "10_post-schema.sql"
              - key: "post-data.sql"
                path: "20_post-data.sql"
  volumeClaimTemplates:
    - metadata:
        name: post-vol
        namespace: {{ .Values.namespace }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: hostpath
        resources:
          requests:
            storage: 250Mi