apiVersion: v1
kind: Service
metadata:
  name: user-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: user-{{ .Release.Name }}
  ports:
    - name: http
      port: 20081
      targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: user-{{ .Release.Name }}
    owner: vzateychuk
spec:
  selector:
    matchLabels:
      app: user-{{ .Release.Name }}
  replicas: {{ .Values.user.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-{{ .Release.Name }}
        owner: vzateychuk
    spec:
      volumes:
        - name: user-store
          persistentVolumeClaim:
            claimName: user-pvc
      initContainers:
        # Checking if the dataBase ready to accept connections
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-cfg
                  key: userdb_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-cfg
                  key: userdb_port
          command: ['sh', '-c',
            'until pg_isready -h $DB_HOST -p $DB_PORT; 
            do echo waiting for database; sleep 2; done;']
      containers:
        - name: user-service
          image: {{ .Values.user.image }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/home/data"
              name: user-store
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-cfg
                  key: userdb_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-cfg
                  key: userdb_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-cfg
                  key: user_db_name
            - name: DB_LOGIN
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: username
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: password

